### ISSUE TITLE
How to connect cctv camera?

### ISSUE THREAD

**Issue by balavenkatesh3322** [AnshulSood11/PPE-Detection-YOLO-Deep_SORT#1]
Do you have any methods to configure cctv camera?

**Comment by AnshulSood11** [comment]
Hi,
It would be helpful if you specify the type of cctv camera you are using and give more details about what you are trying to achieve.

Basically you need to modify ```video_reader = cv2.VideoCapture(i)``` in ```predict.py``` or ```predict_gui.py```. This should work If you are using a USB camera.

Otherwise, if you are using an IP camera, then pass the streaming URL of the camera as argument of ```cv2.VideoCapture()```.

If you are using an Analog camera, then check out [this](https://stackoverflow.com/questions/21790933/grabbing-analog-video-into-python-using-opencv) stackoverflow thread.

Hope this helps.

**Comment by balavenkatesh3322** [comment]
Hey @AnshulSood11 
Thanks for the reply. Let me check my side.
